# Generated by Django 2.1.2 on 2018-10-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('orcamentos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pub', models.DateField(auto_now_add=True, verbose_name='data publicação')),
                ('comentario', models.CharField(max_length=200)),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='')),
                ('prestador_avaliou', models.BooleanField(default=False)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='orcamentos.Orcamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
                ('usuario2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Prestador')),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
                'verbose_name': 'Avaliação',
            },
        ),
    ]
