# Generated by Django 2.1 on 2018-09-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0009_auto_20180923_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pub', models.DateField(verbose_name='data publicação')),
                ('comment', models.CharField(max_length=200)),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Servico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
            ],
        ),
    ]
