# Generated by Django 2.1 on 2018-09-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_pub',
            field=models.DateField(auto_now_add=True, verbose_name='data publicação'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.Orcamento'),
        ),
    ]
