# Generated by Django 2.1 on 2018-09-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_auto_20180924_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='comment',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='servico',
            new_name='orcamento',
        ),
    ]
