# Generated by Django 2.1 on 2018-09-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_auto_20180924_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliado',
            field=models.BooleanField(default=False),
        ),
    ]
