# Generated by Django 2.1 on 2018-09-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_auto_20180924_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliado',
        ),
    ]
