# Generated by Django 2.1 on 2018-09-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0005_remove_avaliacao_avaliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='orcamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='orcamentos.Orcamento'),
        ),
    ]
