# Generated by Django 2.1 on 2018-09-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0006_auto_20180926_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente'),
        ),
    ]
