# Generated by Django 2.1 on 2018-09-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20180923_1256'),
        ('avaliacoes', '0007_auto_20180930_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='usuario2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Prestador'),
        ),
    ]
