# Generated by Django 2.1 on 2018-09-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0008_avaliacao_usuario2'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='prestador_avaliou',
            field=models.BooleanField(default=False),
        ),
    ]
