# Generated by Django 2.1 on 2018-09-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0009_avaliacao_prestador_avaliou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='orcamentos.Orcamento'),
        ),
    ]
