# Generated by Django 2.1 on 2018-09-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0010_auto_20180930_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='prestador_avaliou',
        ),
    ]
