# Generated by Django 2.1 on 2018-09-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0011_remove_avaliacao_prestador_avaliou'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='prestador_avaliou',
            field=models.BooleanField(default=False),
        ),
    ]
