# Generated by Django 2.1 on 2018-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestador',
            options={'verbose_name': 'Prestador', 'verbose_name_plural': 'Prestadores'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='categorias',
            field=models.ManyToManyField(to='catalogo.Categoria'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(default='123456789', max_length=15, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='CPF',
            field=models.CharField(default='12345678', max_length=15, verbose_name='CPF'),
        ),
    ]
