# Generated by Django 2.1 on 2018-09-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0002_auto_20180901_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='categorias',
        ),
        migrations.AddField(
            model_name='prestador',
            name='categorias',
            field=models.ManyToManyField(to='catalogo.Categoria'),
        ),
    ]
