# Generated by Django 2.1 on 2018-09-23 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20180921_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ingressou em'),
            preserve_default=False,
        ),
    ]
