# Generated by Django 2.1 on 2018-09-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_prestador_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Ingressou em'),
        ),
    ]
