# Generated by Django 2.1 on 2018-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20180923_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ingressou em'),
        ),
    ]
