# Generated by Django 2.1 on 2018-09-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0004_auto_20180904_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberta', models.BooleanField(default=True, verbose_name='Status')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('hora_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('hora_aceitacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Cliente')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Endereco')),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalogo.Servico')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
