# Generated by Django 2.1 on 2018-09-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Endereco'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='servico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Servico'),
        ),
    ]
