# Generated by Django 2.1 on 2018-09-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180904_1410'),
        ('orcamentos', '0002_auto_20180904_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField(default=False)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('prestador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Prestador')),
            ],
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='aberta',
            field=models.BooleanField(default=True, verbose_name='Aberta'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='solicitacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.Solicitacao'),
        ),
    ]
