# Generated by Django 2.1 on 2018-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0004_auto_20180904_1410'),
        ('orcamentos', '0003_auto_20180904_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='cliente',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='cliente',
            field=models.ManyToManyField(to='usuarios.Cliente'),
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='endereco',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='endereco',
            field=models.ManyToManyField(to='usuarios.Endereco'),
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='servico',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='servico',
            field=models.ManyToManyField(to='catalogo.Servico'),
        ),
    ]
