# Generated by Django 2.1 on 2018-09-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180904_1410'),
        ('catalogo', '0001_initial'),
        ('orcamentos', '0004_auto_20180904_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='cliente',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='usuarios.Cliente'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='endereco',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Endereco'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='servico',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Servico'),
            preserve_default=False,
        ),
    ]
