# Generated by Django 2.1 on 2018-09-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_auto_20180904_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Prestador'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.Solicitacao'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Endereco', verbose_name='Endereço'),
        ),
    ]
