# Generated by Django 2.1 on 2018-09-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_auto_20180914_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='aberta',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solicitado'), (1, 'Aguardando prestador'), (2, 'Cancelado pelo cliente'), (3, 'Cancelado pelo prestador'), (4, 'Aguardando pagamento'), (5, 'Concluido')], default=0, verbose_name='Status'),
        ),
    ]
