# Generated by Django 2.1 on 2018-09-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0007_auto_20180922_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='descartar',
            field=models.BooleanField(default=False),
        ),
    ]
