# Generated by Django 2.1 on 2018-09-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0008_orcamento_descartar'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='avaliado',
            field=models.BooleanField(default=False),
        ),
    ]
