# Generated by Django 2.1 on 2018-09-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0009_orcamento_avaliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='orcamento_aceito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_aceito', to='orcamentos.Orcamento'),
        ),
    ]
