# Generated by Django 2.1 on 2018-09-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0010_solicitacao_orcamento_aceito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='orcamento_aceito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_aceito', to='orcamentos.Orcamento'),
        ),
    ]
