# Generated by Django 2.1 on 2018-09-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0011_auto_20180924_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='avaliado',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='avaliado',
            field=models.BooleanField(default=False),
        ),
    ]
