# Generated by Django 2.1 on 2018-09-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0012_auto_20180924_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='aceito',
        ),
    ]
