# Generated by Django 2.1 on 2018-09-25 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0013_remove_orcamento_aceito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Endereço', to='usuarios.Endereco', verbose_name='Endereço'),
        ),
    ]
