# Generated by Django 2.1 on 2018-09-25 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0014_auto_20180924_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Endereco', verbose_name='Endereço'),
        ),
    ]
