# Generated by Django 2.1 on 2018-09-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0015_auto_20180924_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='orcamento_aceito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_aceito', to='orcamentos.Orcamento'),
        ),
    ]
