# Generated by Django 2.1 on 2018-09-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0016_auto_20180926_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='avaliado_pelo_prestador',
            field=models.BooleanField(default=False),
        ),
    ]
