# Generated by Django 2.1 on 2018-09-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0017_solicitacao_avaliado_pelo_prestador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao',
            old_name='avaliado_pelo_prestador',
            new_name='prestador_avaliou',
        ),
    ]
